name: Build Wheels
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
jobs:
  build-components:
    runs-on: ubuntu-latest
    name: "build-wheels"
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
      - name: build-wheel
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          poetry version "$PACKAGE_VERSION"
          poetry build -f wheel
      - name: "upload-artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "wheels"
          path: "dist/*.whl"
