name: Build Docs
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: "generate-docs"
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
      - name: mkdocs-build
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          poetry version "$PACKAGE_VERSION"
          poetry run mkdocs build
      - name: "upload-gh-pages"
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"
