name: Check
on:
  workflow_call:
    inputs:
      sha:
        description: 'the git sha to checkout'
        required: true
        type: string
jobs:
  check-components:
    runs-on: ubuntu-latest
    name: "check"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/setup-environment
        id: runner-context
      - name: check
        env:
          PACKAGE_VERSION: "${{ steps.runner-context.outputs.package-version }}"
        run: |
          poetry version "$PACKAGE_VERSION"
          poetry run ruff format --check
          poetry run ruff check
          poetry run pyright
          poetry run pytest
      - name: upload-coverage
        uses: codecov/codecov-action@v5.3.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: microsoft/jl-glove
          name: jl-glove
          verbose: true
